server:
  port: 8080

spring:
  datasource:
      url: jdbc:h2:./build/h2db
      username: sa
      password:
      driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  mail:
    host: localhost
    port: 25
    username: java-obog@localhost
    password: password

vaadin:
  servlet:
    production-mode: false

logging:
  level:
    org.springframework: INFO

app:
  url: http://localhost:8080
  reply: java-obog@localhost
