server:
  port: ${PORT}

spring:
  datasource:
      driverClassName: org.postgresql.Driver
      tomcat:
        max-active: 3
        max-idle: 2
        min-idle: 1
        initial-size: 1
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
  mail:
    host: ${SMTP_SERVER}
    port: ${SMTP_PORT}
    username: ${SMTP_USER}
    password: ${SMTP_PASSWORD}
    properties.mail.smtp:
      auth: true
      starttls.enable: true

vaadin:
  servlet:
    production-mode: true

logging:
  level:
    org.springframework: INFO
    com.github.javatrainingcourse.obogmanager: DEBUG

app:
  url: ${APP_URL}
  reply: ${APP_EMAIL}
